### ISSUE TITLE
ng-repeat fails to show items when filter text is null (1.3.15)

### ISSUE THREAD

**Issue by RickStrahl** [angular/angular.js#11573]
Upgraded to 1.3.15 today in one of my apps and found that an ng-repeat option list with a filter no longer displayed any items. It appears the problem is due to the fact the initial string filter value is null - if I change the initial value to an empty string it works.

```javascript
// intial view model value that doesn't work
vm.searchText = null;
vm.resourceList = [ 
   { ResourceId: "Add", Style=null },
   { ResourceId: "Add_Title", Style="margin-left: 10px" },
   ...
];
```

Then in the HTML to bind:

```html
<option ng-repeat="resource in view.resourceList | filter:view.searchText"
        value="{{resource.ResourceId}}"
        style="{{resource.Style}}">
    {{resource.ResourceId}}
</option>
```

If the intial value of searchText is null the list will not display any items. If the initial value is an empty string (""), however it works fine. This is a breaking change from 1.3.14 where this worked. If by design this should probably go into the breaking change list.

However I think null should be treated like an empty string for search filters I believe so I'd call this a bug...

**Comment by pkozlowski-opensource** [comment]
I believe that it was fixed in master via https://github.com/angular/angular.js/commit/b5002ab62ad6e13f4339e20106e1fdece14912a2. @gkalpak @petebacondarwin shell we back-port it to 1.3.x?

**Comment by gkalpak** [comment]
Since this is a [regression introduced in 1.3.15][1], I think it should be back-ported.

[1]: https://github.com/angular/angular.js/pull/11445#issuecomment-87956330

**Comment by gkalpak** [comment]
Submitted #11617.

**Comment by petebacondarwin** [comment]
Thanks @gkalpak - I think that closes this issue.

**Comment by gkalpak** [comment]
@petebacondarwin, I have submitted the PR, but it isn't merged yet. (So, technically this isn't solved (yet).)

**Comment by RickStrahl** [comment]
Thanks all for looking into this. Much appreciated!

**Comment by issoft-nsiniakevich** [comment]
@gkalpak How can I do `not null` check in this way?
`{ someProperty: !null}` doesn't seems to be working
http://plnkr.co/edit/Apv2qqTGaWQMSpjywnyX?p=preview

`{ someProperty: ''}` it's working, but I don't think that it's very obvious not null check

in the 1.3.15 `{ someProperty: '!null'}` worked fine

**Comment by gkalpak** [comment]
@issoft-nsiniakevich, I am afraid you should either use `{someProp: ''}` (which means _"match against any primitive value (except for null/undefined)"_) or use a custom filter function.
The 1.3.15 behaviour was a regression (introduced after a refactoring in 1.3.6), so 1.3.16 re-instated the "original" behaviour.

**Comment by TheSharpieOne** [comment]
Also worth noting that I have been tracking this ability in an [SO answer](http://stackoverflow.com/a/18644490/1873485).  You can see there that this has changed over the different versions and while it appears that `{someProp: ''}` is recommended, `{someProp: '!!'}` will work as well and has support/worked back through 1.1 (breaking 1.3.6 through 1.3.15 as noted as regression).

**Comment by Nazirkulov** [comment]
Hi dear ang developers! $filter('filter')(array, {property: "!null"}) or
$filter('filter')(array, {property: !null}) does not work . It work for double not ("!!")
$filter('filter')(array, {property: "!!"}) - its norm ?

**Comment by petebacondarwin** [comment]
`$filter('filter')(array, {property: "!null"})` is saying that the array item must not contain the text `"null"`, rather than the property not being `null`.

`$filter('filter')(array, {property: !null})` is equivalent to `$filter('filter')(array, {property: true})` since the `!null` expression will be evaluated before being pass to the filter.

It seems that `"!!"` is the best approach to take in this scenario.

**Comment by gkalpak** [comment]
To expand a bit on what @petebacondarwin said:

In the current version (which hasn't changed iirc since 1.4.x), `{prop: ''}` (which is equivalent to `{prop: '!!'}` - this is a bug in `filterFilter`, but ¯\\\_(ツ)\_/¯ ) matches all objects that have a primitive<sup>*</sup> `prop` value except `null` or `undefined`. Similarly, `{prop: '!'}` matches the opposite (`null`, `undefined`, or non-primitive<sup*</sup>):

```js
const expr = {foo: ''};
filterFilter([{foo: 'bar'}, {foo: true}, {foo: 1}], expr)  //--> All match
filterFilter([{foo: null}, {foo: undefined}, {foo: {}}], expr)  //--> No match

const expr = {foo: '!'};
filterFilter([{foo: 'bar'}, {foo: true}, {foo: 1}], expr)  //--> No match
filterFilter([{foo: null}, {foo: undefined}, {foo: {}}], expr)  //--> All match
```

*: Objects with a custom `toString()` method are matched using the result of their `toString()`.
