### ISSUE TITLE
ngClass on ngView is not in sync since 1.4.0-rc.0

### ISSUE THREAD

**Issue by m4r71n** [angular/angular.js#12080]
Working example with 1.4.0-beta.6: http://plnkr.co/edit/aBcSTUO8Et17Y8MSWNJL?p=preview
![2015-06-10_221405](https://cloud.githubusercontent.com/assets/6043876/8092983/2a1bd1a2-0fbe-11e5-8954-585521013ec4.png)

Broken example with 1.4.0-rc.0: http://plnkr.co/edit/22mLv7fXesMVXfEwX6Yt?p=preview
![2015-06-10_221455](https://cloud.githubusercontent.com/assets/6043876/8092986/2d8b14e2-0fbe-11e5-9679-1bee90768e8a.png)

I'm not sure if this is a bug or if I need to change something because of c8700f04fb6fb5dc21ac24de8665c0476d6db5ef?

**Comment by Narretz** [comment]
What exactly is the problem? Do your animations not work anymore?
I cannot say with 100% certainty that the first example is correct, because I am not sure if the view animations are supposed to happen exactly at the same time.

**Comment by Narretz** [comment]
Have you tried with 1.4.1?

**Comment by m4r71n** [comment]
I've updated the examples. With 1.3.16 and 1.4.0-beta.6 both ngViews slide at the same time in the same direction. With 1.4.0-rc.0 and 1.4.1 they sometimes crossover or slide away from each other.
By clicking the buttons in this order you can see the difference: `2,3,2,1,2`

**Comment by matsko** [comment]
There are two bugs that exist here:

1. There is an issue with ngClass in 1.4.x
2. With the way that ngView works it destroys the scope first and then animates so the classes on the element don't get picked up in time.

I will aim to have both issues fixed in 1.4.2.

**Comment by matsko** [comment]
Alright so this isn't an issue with ngClass (I tested this against #12248 and it didn't fix it). So it looks like it is #2 on the list.

**Comment by Narretz** [comment]
@matsko The problem still repdroduces in the current snapshot.

**Comment by Narretz** [comment]
Still broken in 1.4.6 :(

**Comment by alexlamsl** [comment]
Applying a quick hack around `$animate.{add,remove}Class()` which performs the `class` manipulation before the proper queuing seems to solve the issue visually:

http://plnkr.co/edit/f7rjvA2waeVGPSWyAoor?p=preview

**Comment by matsko** [comment]
I am aware of this issue and I will have a look at it tomorrow. Sorry for the delays and thank you for keeping this issue going.
